[workspace]
members = [
    "kernel/util",
    "kernel/generic",
    "kernel/generic/derive",
    "kernel/generic/examples",
    "kernel/notation/generic",
    "kernel/notation/slate",
    "kernel/metalogic",
    "kernel/metalogic/mltt",
]
