[package]
name = "slate-lang-def"
version = "0.1.0"
edition = "2021"

[dependencies]
lang-def = { git = "https://github.com/SReichelt/lang-tools.git" }
lang-test = { git = "https://github.com/SReichelt/lang-tools.git" }
smallvec = { version = "1.13.2", features = ["union", "const_generics"] }
