[package]
name = "slate-kernel-notation-slate"
version = "0.1.0"
edition = "2021"

[dependencies]
slate-kernel-notation-generic = { path = "../generic" }
slate-kernel-util = { path = "../../util" }
anyhow = "1.0.81"
