[package]
name = "slate-kernel-generic-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
slate-kernel-generic = { path = ".." }
slate-kernel-generic-derive = { path = "../derive" }
anyhow = "1.0.81"
smallvec = { version = "1.13", features = ["union", "const_generics"] }
