[package]
name = "slate-kernel-generic"
version = "0.1.0"
edition = "2021"

[dependencies]
slate-kernel-util = { path = "../util" }
anyhow = "1.0.69"
smallvec = { version = "1.10", features = ["union", "const_generics"] }
